describe("localreview.config", function()
  local config

  before_each(function()
    package.loaded["localreview.config"] = nil
    config = require("localreview.config")
  end)

  describe("M.defaults", function()
    it("contains all 3 sections: keys, virtual_text, git", function()
      assert.is_not_nil(config.defaults.keys)
      assert.is_not_nil(config.defaults.virtual_text)
      assert.is_not_nil(config.defaults.git)
    end)

    it("has annotate default as <leader>ra", function()
      assert.are.equal("<leader>ra", config.defaults.keys.annotate)
    end)

    it("has all 6 key bindings", function()
      assert.are.equal("<leader>ra", config.defaults.keys.annotate)
      assert.are.equal("<leader>rv", config.defaults.keys.view)
      assert.are.equal("<leader>rd", config.defaults.keys.delete)
      assert.are.equal("]r", config.defaults.keys.next_review)
      assert.are.equal("[r", config.defaults.keys.prev_review)
      assert.are.equal("<leader>rt", config.defaults.keys.telescope)
    end)
  end)

  describe("M.setup", function()
    it("with empty opts results in values matching defaults", function()
      config.setup({})
      assert.are.equal(config.defaults.keys.annotate, config.values.keys.annotate)
      assert.are.equal(config.defaults.keys.view, config.values.keys.view)
      assert.are.equal(config.defaults.keys.delete, config.values.keys.delete)
      assert.are.equal(config.defaults.keys.next_review, config.values.keys.next_review)
      assert.are.equal(config.defaults.keys.prev_review, config.values.keys.prev_review)
      assert.are.equal(config.defaults.keys.telescope, config.values.keys.telescope)
      assert.are.equal(config.defaults.virtual_text.enabled, config.values.virtual_text.enabled)
      assert.are.equal(config.defaults.virtual_text.hl_group, config.values.virtual_text.hl_group)
      assert.are.equal(config.defaults.git.track_commit, config.values.git.track_commit)
    end)

    it("deep merges partial keys override, keeping other defaults", function()
      config.setup({ keys = { annotate = "<leader>xa" } })
      assert.are.equal("<leader>xa", config.values.keys.annotate)
      assert.are.equal("<leader>rv", config.values.keys.view)
      assert.are.equal("<leader>rd", config.values.keys.delete)
      assert.are.equal("]r", config.values.keys.next_review)
      assert.are.equal("[r", config.values.keys.prev_review)
      assert.are.equal("<leader>rt", config.values.keys.telescope)
    end)

    it("keys = false sets values.keys to literal false", function()
      config.setup({ keys = false })
      assert.is_false(config.values.keys)
    end)

    it("deep merges partial virtual_text override", function()
      config.setup({ virtual_text = { hl_group = "Special" } })
      assert.are.equal("Special", config.values.virtual_text.hl_group)
      assert.are.equal(true, config.values.virtual_text.enabled)
    end)
  end)

  describe("M.validate_user_opts", function()
    it("returns unknown keys for invalid options", function()
      local unknown = config.validate_user_opts({ kets = {}, foo = 1 })
      table.sort(unknown)
      assert.are.equal(2, #unknown)
      assert.are.equal("foo", unknown[1])
      assert.are.equal("kets", unknown[2])
    end)

    it("returns empty list for valid options", function()
      local unknown = config.validate_user_opts({ keys = {}, virtual_text = {} })
      assert.are.equal(0, #unknown)
    end)

    it("does NOT flag keys when keys = false", function()
      local unknown = config.validate_user_opts({ keys = false })
      assert.are.equal(0, #unknown)
    end)
  end)
end)
