describe("telescope", function()
  local telescope_mod = require("localreview.telescope")

  describe("_find_review_files", function()
    it("returns a table with matching review files", function()
      local tmp = vim.fn.tempname()
      vim.fn.mkdir(tmp, "p")
      vim.fn.writefile({ '{"version":1,"reviews":{}}' }, tmp .. "/.test.lua.reviews.json")
      local files = telescope_mod._find_review_files(tmp)
      assert.is_table(files)
      assert.equals(1, #files)
      assert.truthy(files[1]:match("%.test%.lua%.reviews%.json$"))
      vim.fn.delete(tmp, "rf")
    end)

    it("returns empty table for dir with no review files", function()
      local tmp = vim.fn.tempname()
      vim.fn.mkdir(tmp, "p")
      local files = telescope_mod._find_review_files(tmp)
      assert.is_table(files)
      assert.equals(0, #files)
      vim.fn.delete(tmp, "rf")
    end)

    it("finds review files in subdirectories", function()
      local tmp = vim.fn.tempname()
      vim.fn.mkdir(tmp .. "/sub/dir", "p")
      vim.fn.writefile({ '{"version":1,"reviews":{}}' }, tmp .. "/sub/dir/.deep.lua.reviews.json")
      local files = telescope_mod._find_review_files(tmp)
      assert.is_table(files)
      assert.equals(1, #files)
      assert.truthy(files[1]:match("deep%.lua%.reviews%.json$"))
      vim.fn.delete(tmp, "rf")
    end)
  end)
end)
